version: '2.1'

services:
  app:
    image: node-express
    build: .
    volumes:
      - .:/build
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo'
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod --smallfiles
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
